language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: devfesthyd18
  token:
    secure: Q/DovsKYmPoeDm1v8H8TgrVlcX7rfHMfBjx2Cu9NQJs5XnAaLNT+XugYMbtBPh/VsZ1cziodbQXSVt88hUcypHq6pBzcO5tpKAgT/faFh69+u04qng9LE/nZ8aYuN5NRcI5Df3stWCRKef7V85I1jF1XkTuip2SO5o5cZkAfaAO4+ITz2UsFBL1Y5bOeDjFV80X2DAG0FYYTSeN1gAg/xke39DHwdO18mY65YAQKdkOD+yoc0xLLsTGFZqdd6I2rlLMf0kfEPOv/BDdSzdj2Vi/wVjC/JBMerBCXqU88GStiS2PzouyUdWMO1qVIklmf7/TTGcrIpVD5pYm8hUgoNVYRf5Pwzd7RkX+Zkn/azoiBlecerfKJvhVB3Qv86LTg0/cdFUQgl10F/ui023LCNFeaFX3wvvBOYC27f5tzufrTLjFoWsGDU995i33zEDhlENKyetIZdilQKIhz4MqoyrBQcaH+64x8hWtBXSODxGGMyW25ZQjV+50l/EAnC2CSOCuXVSjKcCAoTsWEjsTJQ0QKqNN2vFuZjcdx15jfDoMAoO39zqHQgUqm6AKes3xKyXi0OqToo37pXKGZs3foiIN4X4S28KrCrEIzgraxyEZ0Ls/aPP4HKQqj7UVT4Z1138jfvUVhCgIjuWTl78VHBhMjBKjPNMH8soRi0To0yfU=